# Generated by Django 2.1.2 on 2018-12-24 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_auto_20181224_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='')),
                ('assignees', models.ManyToManyField(to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.PositiveIntegerField()),
                ('bottom', models.PositiveIntegerField()),
                ('left', models.PositiveIntegerField()),
                ('right', models.PositiveIntegerField()),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Signature'), (2, 'Name'), (3, 'Date')])),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document_signing.Document')),
            ],
        ),
    ]
