# Generated by Django 2.1.2 on 2019-01-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20181224_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_status_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
