# Generated by Django 2.1.2 on 2019-01-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user_login_status_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_token_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
